### ISSUE TITLE
com.snappydb.SnappydbException: Maybe you tried to retrieve an array using this method ? please use getObjectArray instead java.lang.IndexOutOfBoundsException: Invalid index 104, size is 7 

### ISSUE THREAD

**Issue by colymore** [nhachicha/SnappyDB#39]
Im getting this error in random cases, when app crash, i do same steps and works fine sometimes.
What can be happenning?

com.snappydb.SnappydbException: Maybe you tried to retrieve an array using this method ? please use getObjectArray instead java.lang.IndexOutOfBoundsException: Invalid index 104, size is 7
Serialization trace:
date (com.firext.android.model.bbdd.DBWork)
at com.snappydb.internal.DBImpl.getObject(DBImpl.java:280)
at com.firext.android.data.NoSQLWorksPersistenceImpl.getWorkById(NoSQLWorksPersistenceImpl.java:68)
at com.firext.android.data.NoSQLWorksPersistenceImpl.getReportInWorkById(NoSQLWorksPersistenceImpl.java:143)
at com.firext.android.jobs.GetReplieGroupsForWorkAndReport.onRun(GetReplieGroupsForWorkAndReport.java:31)
at com.path.android.jobqueue.BaseJob.safeRun(BaseJob.java:108)
at com.path.android.jobqueue.JobHolder.safeRun(JobHolder.java:60)
at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:201)
at java.lang.Thread.run(Thread.java:841)

**Comment by JoanZapata** [comment]
I get the same thing. It seems to be related with writing/reading 2 keys at the same time.
Isn't SnappyDb thread-safe ?

**Comment by JoanZapata** [comment]
I can confirm, it happens each time 2 `read` operations are executed concurrently.

**Comment by colymore** [comment]
Maybe doing a syncronized method should fix it.

**Comment by nhachicha** [comment]
Hi, SnappyDB is not thread safe, here is an example of how you can use it on multi thread environment 
[DatabaseImpl](https://github.com/theappbusiness/kc-android/blob/master/app/src/main/java/com/nabilhachicha/kc/data/DatabaseImpl.java)
_taken from the [King's Cross](https://github.com/theappbusiness/kc-android) project_

**Comment by gajraj-hinkhoj** [comment]
I am also facing this issue, any help?

**Comment by colymore** [comment]
Just be sure that only one thread is using database. Maybe a singleton class syncronized.

**Comment by blaine0611** [comment]
I got this problem too, I have tried singleton class but it still existed. Can anyone help me?

**Comment by francescortiz** [comment]
I get the error when storing long strings. In my case the solution has been to convert the strings to byte[] before storing them.

**Comment by francescortiz** [comment]
Digging further I found that getObject(key, String.class) misbehaves, while get(key) works as expected. So in my wrapper I added check for incoming the incoming class and if it is a String I redirect to the working function.

**Comment by matheusaguiardev** [comment]
Check constructor. 

> public void Example(){}

**Comment by programmer-1** [comment]
Make sure all your classes related to db have empty constructor.
